name: Deployment pipeline for Menu_Get svc

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "test"
        type: choice
        options:
        - test
        - staging
        - uat
        - prod

env:
  STACK_NAME: MenuGetStack

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs: 
  build_and_deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment || 'dev' }}
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    permisions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup aws-sam cli
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Dtermine target environment
      id: set-env
      run: |
        ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}
        echo "ENVIRONMENT=${ENVIRONMENT}" >> $
        echo "ENVIRONMENT_UPPER=$(echo $ENVIRONMENT | tr '[:lower]' '[:upper]')" >> $GITHUB_ENV

    - name: Configure AWS credentials using OIDC token
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-aasume: arn:aws:iam::${{ secrets[format('AWS_ACCOUNT_ID_${{ env.ENVIRONMENT_UPPER }}')] }}:role/GitHubActionsDeployRole
        role-session-name: menu-get-svc-dev-session
        aws-region: us-east-1

    - name: Build app
      run: |
        sam build --template-file template.yaml

    - name: Deploy the app
      run: |
        sam deploy
          --no-progressbar \
          --resolve-s3 \
          --role-arn arn:aws:iam::${{ secrets[format('AWS_ACCOUNT_ID_${{ env.ENVIRONMENT_UPPER }}')] }}:role/GitHubActionsDeployRole \
          --stack-name $STACK_NAME-${{ env.ENVIRONMENT }}
      