name: Deployment pipeline for Menu_Get svc

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python_version: '3.11'
    
    - name: Install dependencies for unit testing
      run: |
        cd tests
        pip install -r requirements.txt

    - name: Lint the code
      run: |
        pylint ./unit

    - name: Run the tests
      run: pytest ./unit
      
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup aws-sam cli
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup aws creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-aasume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_DEV }}:role/MenuGetSvcDeployDevRole
        role-session-name: menu-get-svc-dev-session
        aws-region: us-east-1

    - name: Build app
      run: |
        sam build --template-file template.yaml

    - name: Deploy the app
      run: |
        sam deploy
          --no-progressbar \
          --resolve-s3 \
          --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_DEV }}:role/MenuGetSvcDeployDevRole \
          --stack-name MenuGetStack
      